[[features]]
title = "New resource"
description = "`oxide_ssh_key` [#211](https://github.com/oxidecomputer/terraform-provider-oxide/pull/211)"

[[features]]
title = "New data source"
description = "`oxide_ssh_key` [#211](https://github.com/oxidecomputer/terraform-provider-oxide/pull/211)"

[[enhancements]]
title = "Documentation"
description = "Various documentation clarifications [#185](https://github.com/oxidecomputer/terraform-provider-oxide/pull/185), [#218](https://github.com/oxidecomputer/terraform-provider-oxide/pull/218)"

[[features]]
title = "New resource"
description = "`oxide_vpc_firewall_rules` [#220](https://github.com/oxidecomputer/terraform-provider-oxide/pull/220)"

[[breaking]]
title = "Image resource"
description = "Image creation via URL is no longer supported [#XXX](https://github.com/oxidecomputer/terraform-provider-oxide/pull/XXX)"

[[enhancements]]
title = "Image resource"
description = "Deletes are now supported [#XXX](https://github.com/oxidecomputer/terraform-provider-oxide/pull/XXX)"