[[breaking]]
title = ""
description = ""

[[features]]
title = "New data source"
description = "`oxide_disk` [#539](https://github.com/oxidecomputer/terraform-provider-oxide/pull/539)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""
