[[breaking]]
title = "Changed schema of `external_ips` in the `oxide_instance` resource"
description = "The `external_ips` attribute of the `oxide_instance` resource is now an object instead of a list. [#597](https://github.com/oxidecomputer/terraform-provider-oxide/pull/597)."

[[features]]
title = "New resource"
description = "`oxide_address_lot` [#489](https://github.com/oxidecomputer/terraform-provider-oxide/pull/489)."

[[features]]
title = "New data source"
description = "`oxide_address_lot` [#489](https://github.com/oxidecomputer/terraform-provider-oxide/pull/489)."

[[features]]
title = "Support `OXIDE_PROFILE`"
description = "Added support for the `OXIDE_PROFILE` environment variable within the provider configuration. [#589](https://github.com/oxidecomputer/terraform-provider-oxide/pull/589)."

[[features]]
title = "Support `config_dir` and `insecure_skip_verify`"
description = "Added support for the `config_dir` and `insecure_skip_verify` provider configuration. [#595](https://github.com/oxidecomputer/terraform-provider-oxide/pull/595)."

[[features]]
title = "Support `disk_type` in disk resource."
description = "Added support for the `disk_type` attribute for the `oxide_disk` resource. [#587](https://github.com/oxidecomputer/terraform-provider-oxide/pull/587)."

[[features]]
title = "Support IPv6 and dual-stack network interfaces in `oxide_instance`."
description = "Added support for IPv6 and dual-stack network interfaces in the `oxide_instance` resource. [#591](https://github.com/oxidecomputer/terraform-provider-oxide/pull/591)."

[[features]]
title = "New resource"
description = "`oxide_subnet_pool` [#614](https://github.com/oxidecomputer/terraform-provider-oxide/pull/614)."

[[features]]
title = "New resource"
description = "`oxide_subnet_pool_member` [#614](https://github.com/oxidecomputer/terraform-provider-oxide/pull/614)."

[[features]]
title = "New data source"
description = "`oxide_subnet_pool` [#614](https://github.com/oxidecomputer/terraform-provider-oxide/pull/614)."

[[features]]
title = "New resource"
description = "`oxide_subnet_pool_silo_link` [#615](https://github.com/oxidecomputer/terraform-provider-oxide/pull/615)."

[[features]]
title = "New resource"
description = "`oxide_switch_port_settings` [#475](https://github.com/oxidecomputer/terraform-provider-oxide/pull/475)."

[[features]]
title = "Support IPv6 external IPs in `oxide_instance`."
description = "Added support for IPv6 external IPs in the `oxide_instance` resource. [#597](https://github.com/oxidecomputer/terraform-provider-oxide/pull/597)."

[[enhancements]]
title = "`oxide_instance` attribute deprecation"
description = "The `host_name` attribute on the `oxide_instance` resource has been deprecated in favor of `hostname`. The `host_name` attribute will be removed in the next minor version of the provider. [#577](https://github.com/oxidecomputer/terraform-provider-oxide/pulls/577)."

[[enhancements]]
title = "IPv6 support for `oxide_floating_ip`"
description = "Add IPv6 support for the `oxide_floating_ip` resource. [#608](https://github.com/oxidecomputer/terraform-provider-oxide/pull/608)"

[[bugs]]
title = ""
description = ""
