[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_anti_affinity_group` [#415](https://github.com/oxidecomputer/terraform-provider-oxide/pull/415)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""